name: CI

on: [pull_request, push]

jobs:
  install:
    name: Instalando packages
    runs-on: ubuntu-latest
    steps:
      # dar acesso da máquina virtual ao projeto
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules

      - name: Instalando dependencias
        run: npm install

  testing:
      - name: Testando
        run: npm test

        


name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
